// <auto-generated/>

#nullable enable

using Microsoft.CodeAnalysis.Lightup;
using System;

namespace Microsoft.CodeAnalysis.CSharp.Syntax.Lightup
{
    /// <summary>Added in Roslyn version 3.8.0.0</summary>
    public readonly struct FunctionPointerTypeSyntaxWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.FunctionPointerTypeSyntax";

        public static readonly Type? WrappedType;

        private static readonly Func<TypeSyntax?, SyntaxToken> AsteriskTokenFunc;
        private static readonly Func<TypeSyntax?, FunctionPointerCallingConventionSyntaxWrapper> CallingConventionFunc;
        private static readonly Func<TypeSyntax?, SyntaxToken> DelegateKeywordFunc;
        private static readonly Func<TypeSyntax?, FunctionPointerParameterListSyntaxWrapper> ParameterListFunc;

        private static readonly Action<TypeSyntax?, CSharpSyntaxVisitor> AcceptFunc0;
        private static readonly Func<TypeSyntax?, FunctionPointerParameterSyntaxWrapper[], FunctionPointerTypeSyntaxWrapper> AddParameterListParametersFunc1;
        private static readonly Func<TypeSyntax?, SyntaxToken, SyntaxToken, FunctionPointerCallingConventionSyntaxWrapper, FunctionPointerParameterListSyntaxWrapper, FunctionPointerTypeSyntaxWrapper> UpdateFunc2;
        private static readonly Func<TypeSyntax?, SyntaxToken, FunctionPointerTypeSyntaxWrapper> WithAsteriskTokenFunc3;
        private static readonly Func<TypeSyntax?, FunctionPointerCallingConventionSyntaxWrapper, FunctionPointerTypeSyntaxWrapper> WithCallingConventionFunc4;
        private static readonly Func<TypeSyntax?, SyntaxToken, FunctionPointerTypeSyntaxWrapper> WithDelegateKeywordFunc5;
        private static readonly Func<TypeSyntax?, FunctionPointerParameterListSyntaxWrapper, FunctionPointerTypeSyntaxWrapper> WithParameterListFunc6;

        private readonly TypeSyntax? wrappedObject;

        static FunctionPointerTypeSyntaxWrapper()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);

            AsteriskTokenFunc = LightupHelper.CreateGetAccessor<TypeSyntax?, SyntaxToken>(WrappedType, nameof(AsteriskToken));
            CallingConventionFunc = LightupHelper.CreateGetAccessor<TypeSyntax?, FunctionPointerCallingConventionSyntaxWrapper>(WrappedType, nameof(CallingConvention));
            DelegateKeywordFunc = LightupHelper.CreateGetAccessor<TypeSyntax?, SyntaxToken>(WrappedType, nameof(DelegateKeyword));
            ParameterListFunc = LightupHelper.CreateGetAccessor<TypeSyntax?, FunctionPointerParameterListSyntaxWrapper>(WrappedType, nameof(ParameterList));

            AcceptFunc0 = LightupHelper.CreateVoidMethodAccessor<TypeSyntax?, CSharpSyntaxVisitor>(WrappedType, nameof(Accept));
            AddParameterListParametersFunc1 = LightupHelper.CreateMethodAccessor<TypeSyntax?, FunctionPointerParameterSyntaxWrapper[], FunctionPointerTypeSyntaxWrapper>(WrappedType, nameof(AddParameterListParameters));
            UpdateFunc2 = LightupHelper.CreateMethodAccessor<TypeSyntax?, SyntaxToken, SyntaxToken, FunctionPointerCallingConventionSyntaxWrapper, FunctionPointerParameterListSyntaxWrapper, FunctionPointerTypeSyntaxWrapper>(WrappedType, nameof(Update));
            WithAsteriskTokenFunc3 = LightupHelper.CreateMethodAccessor<TypeSyntax?, SyntaxToken, FunctionPointerTypeSyntaxWrapper>(WrappedType, nameof(WithAsteriskToken));
            WithCallingConventionFunc4 = LightupHelper.CreateMethodAccessor<TypeSyntax?, FunctionPointerCallingConventionSyntaxWrapper, FunctionPointerTypeSyntaxWrapper>(WrappedType, nameof(WithCallingConvention));
            WithDelegateKeywordFunc5 = LightupHelper.CreateMethodAccessor<TypeSyntax?, SyntaxToken, FunctionPointerTypeSyntaxWrapper>(WrappedType, nameof(WithDelegateKeyword));
            WithParameterListFunc6 = LightupHelper.CreateMethodAccessor<TypeSyntax?, FunctionPointerParameterListSyntaxWrapper, FunctionPointerTypeSyntaxWrapper>(WrappedType, nameof(WithParameterList));
        }

        private FunctionPointerTypeSyntaxWrapper(TypeSyntax? obj)
        {
            wrappedObject = obj;
        }

        public readonly SyntaxToken AsteriskToken
            => AsteriskTokenFunc(wrappedObject);

        public readonly FunctionPointerCallingConventionSyntaxWrapper CallingConvention
            => CallingConventionFunc(wrappedObject);

        public readonly SyntaxToken DelegateKeyword
            => DelegateKeywordFunc(wrappedObject);

        public readonly FunctionPointerParameterListSyntaxWrapper ParameterList
            => ParameterListFunc(wrappedObject);

        public static implicit operator TypeSyntax?(FunctionPointerTypeSyntaxWrapper obj)
            => obj.Unwrap();

        public static bool Is(object? obj)
            => LightupHelper.Is(obj, WrappedType);

        public static FunctionPointerTypeSyntaxWrapper As(object? obj)
        {
            var obj2 = LightupHelper.As<TypeSyntax>(obj, WrappedType);
            return new FunctionPointerTypeSyntaxWrapper(obj2);
        }

        public TypeSyntax? Unwrap()
            => wrappedObject;

        public readonly void Accept(CSharpSyntaxVisitor visitor)
            => AcceptFunc0(wrappedObject, visitor);

        public readonly FunctionPointerTypeSyntaxWrapper AddParameterListParameters(params FunctionPointerParameterSyntaxWrapper[] items)
            => AddParameterListParametersFunc1(wrappedObject, items);

        public readonly FunctionPointerTypeSyntaxWrapper Update(SyntaxToken delegateKeyword, SyntaxToken asteriskToken, FunctionPointerCallingConventionSyntaxWrapper callingConvention, FunctionPointerParameterListSyntaxWrapper parameterList)
            => UpdateFunc2(wrappedObject, delegateKeyword, asteriskToken, callingConvention, parameterList);

        public readonly FunctionPointerTypeSyntaxWrapper WithAsteriskToken(SyntaxToken asteriskToken)
            => WithAsteriskTokenFunc3(wrappedObject, asteriskToken);

        public readonly FunctionPointerTypeSyntaxWrapper WithCallingConvention(FunctionPointerCallingConventionSyntaxWrapper callingConvention)
            => WithCallingConventionFunc4(wrappedObject, callingConvention);

        public readonly FunctionPointerTypeSyntaxWrapper WithDelegateKeyword(SyntaxToken delegateKeyword)
            => WithDelegateKeywordFunc5(wrappedObject, delegateKeyword);

        public readonly FunctionPointerTypeSyntaxWrapper WithParameterList(FunctionPointerParameterListSyntaxWrapper parameterList)
            => WithParameterListFunc6(wrappedObject, parameterList);
    }
}
