// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp.Syntax.Lightup;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.CSharp.Syntax.Lightup
{
    /// <summary>Class added in version 4.4.0.0 of Roslyn.</summary>
    public readonly struct SlicePatternSyntaxWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.SlicePatternSyntax";

        public static readonly Type? WrappedType;

        private delegate SyntaxToken DotDotTokenGetterDelegate(PatternSyntax? _obj);
        private delegate PatternSyntax? PatternGetterDelegate(PatternSyntax? _obj);

        private delegate void AcceptDelegate0(PatternSyntax? _obj, CSharpSyntaxVisitor visitor);
        private delegate SlicePatternSyntaxWrapper UpdateDelegate1(PatternSyntax? _obj, SyntaxToken dotDotToken, PatternSyntax? pattern);
        private delegate SlicePatternSyntaxWrapper WithDotDotTokenDelegate2(PatternSyntax? _obj, SyntaxToken dotDotToken);
        private delegate SlicePatternSyntaxWrapper WithPatternDelegate3(PatternSyntax? _obj, PatternSyntax? pattern);

        private static readonly DotDotTokenGetterDelegate DotDotTokenGetterFunc;
        private static readonly PatternGetterDelegate PatternGetterFunc;

        private static readonly AcceptDelegate0 AcceptFunc0;
        private static readonly UpdateDelegate1 UpdateFunc1;
        private static readonly WithDotDotTokenDelegate2 WithDotDotTokenFunc2;
        private static readonly WithPatternDelegate3 WithPatternFunc3;

        private readonly PatternSyntax? wrappedObject;

        static SlicePatternSyntaxWrapper()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);

            DotDotTokenGetterFunc = LightupHelper.CreateInstanceGetAccessor<DotDotTokenGetterDelegate>(WrappedType, nameof(DotDotToken));
            PatternGetterFunc = LightupHelper.CreateInstanceGetAccessor<PatternGetterDelegate>(WrappedType, nameof(Pattern));

            AcceptFunc0 = LightupHelper.CreateInstanceMethodAccessor<AcceptDelegate0>(WrappedType, nameof(Accept));
            UpdateFunc1 = LightupHelper.CreateInstanceMethodAccessor<UpdateDelegate1>(WrappedType, nameof(Update));
            WithDotDotTokenFunc2 = LightupHelper.CreateInstanceMethodAccessor<WithDotDotTokenDelegate2>(WrappedType, nameof(WithDotDotToken));
            WithPatternFunc3 = LightupHelper.CreateInstanceMethodAccessor<WithPatternDelegate3>(WrappedType, nameof(WithPattern));
        }

        private SlicePatternSyntaxWrapper(PatternSyntax? obj)
        {
            wrappedObject = obj;
        }

        /// <summary>Property added in version 4.4.0.0 of Roslyn.</summary>
        public readonly SyntaxToken DotDotToken
        {
            get => DotDotTokenGetterFunc(wrappedObject);
        }

        /// <summary>Property added in version 4.4.0.0 of Roslyn.</summary>
        public readonly PatternSyntax? Pattern
        {
            get => PatternGetterFunc(wrappedObject);
        }

        public static implicit operator PatternSyntax?(SlicePatternSyntaxWrapper obj)
            => obj.Unwrap();

        public static bool Is(object? obj)
            => LightupHelper.Is(obj, WrappedType);

        public static SlicePatternSyntaxWrapper As(object? obj)
        {
            var obj2 = LightupHelper.As<PatternSyntax>(obj, WrappedType);
            return new SlicePatternSyntaxWrapper(obj2);
        }

        public PatternSyntax? Unwrap()
            => wrappedObject;

        /// <summary>Method added in version 4.4.0.0 of Roslyn.</summary>
        public readonly void Accept(CSharpSyntaxVisitor visitor)
            => AcceptFunc0(wrappedObject, visitor);

        /// <summary>Method added in version 4.4.0.0 of Roslyn.</summary>
        public readonly SlicePatternSyntaxWrapper Update(SyntaxToken dotDotToken, PatternSyntax? pattern)
            => UpdateFunc1(wrappedObject, dotDotToken, pattern);

        /// <summary>Method added in version 4.4.0.0 of Roslyn.</summary>
        public readonly SlicePatternSyntaxWrapper WithDotDotToken(SyntaxToken dotDotToken)
            => WithDotDotTokenFunc2(wrappedObject, dotDotToken);

        /// <summary>Method added in version 4.4.0.0 of Roslyn.</summary>
        public readonly SlicePatternSyntaxWrapper WithPattern(PatternSyntax? pattern)
            => WithPatternFunc3(wrappedObject, pattern);
    }
}
