// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp.Syntax.Lightup;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.CSharp.Syntax.Lightup
{
    public static class TypeSyntaxExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.Syntax.TypeSyntax";

        private delegate Boolean IsNintGetterDelegate(TypeSyntax? _obj);
        private delegate Boolean IsNotNullGetterDelegate(TypeSyntax? _obj);
        private delegate Boolean IsNuintGetterDelegate(TypeSyntax? _obj);

        private static readonly IsNintGetterDelegate IsNintGetterFunc;
        private static readonly IsNotNullGetterDelegate IsNotNullGetterFunc;
        private static readonly IsNuintGetterDelegate IsNuintGetterFunc;

        static TypeSyntaxExtensions()
        {
            var wrappedType = LightupHelper.FindType(WrappedTypeName);

            IsNintGetterFunc = LightupHelper.CreateInstanceGetAccessor<IsNintGetterDelegate>(wrappedType, nameof(IsNint));
            IsNotNullGetterFunc = LightupHelper.CreateInstanceGetAccessor<IsNotNullGetterDelegate>(wrappedType, nameof(IsNotNull));
            IsNuintGetterFunc = LightupHelper.CreateInstanceGetAccessor<IsNuintGetterDelegate>(wrappedType, nameof(IsNuint));
        }

        /// <summary>Property added in version 3.8.0.0 of Roslyn.</summary>
        public static Boolean IsNint(this TypeSyntax _obj)
            => IsNintGetterFunc(_obj);

        /// <summary>Property added in version 3.8.0.0 of Roslyn.</summary>
        public static Boolean IsNotNull(this TypeSyntax _obj)
            => IsNotNullGetterFunc(_obj);

        /// <summary>Property added in version 3.8.0.0 of Roslyn.</summary>
        public static Boolean IsNuint(this TypeSyntax _obj)
            => IsNuintGetterFunc(_obj);
    }
}
