// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Operations.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Lightup
{
    public static class IAssemblySymbolExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.IAssemblySymbol";

        private static readonly Type? WrappedType; // NOTE: Used via reflection

        private delegate ImmutableArray<INamedTypeSymbol> GetForwardedTypesDelegate0(IAssemblySymbol? _obj);

        private static readonly GetForwardedTypesDelegate0 GetForwardedTypesFunc0;

        static IAssemblySymbolExtensions()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);

            GetForwardedTypesFunc0 = LightupHelper.CreateInstanceMethodAccessor<GetForwardedTypesDelegate0>(WrappedType, nameof(GetForwardedTypes));
        }

        /// <summary>Method added in version 3.8.0.0 of Roslyn.</summary>
        public static ImmutableArray<INamedTypeSymbol> GetForwardedTypes(this IAssemblySymbol _obj)
            => GetForwardedTypesFunc0(_obj);
    }
}
