// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Interface added in Roslyn version 4.4.0.0</summary>
    public readonly struct IImportScopeWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.IImportScope";

        public static readonly Type? WrappedType;

        private delegate ImmutableArray<IAliasSymbol> AliasesGetterDelegate(object? _obj);
        private delegate ImmutableArray<IAliasSymbol> ExternAliasesGetterDelegate(object? _obj);
        private delegate ImmutableArray<ImportedNamespaceOrTypeWrapper> ImportsGetterDelegate(object? _obj);
        private delegate ImmutableArray<ImportedXmlNamespaceWrapper> XmlNamespacesGetterDelegate(object? _obj);

        private static readonly AliasesGetterDelegate AliasesGetterFunc;
        private static readonly ExternAliasesGetterDelegate ExternAliasesGetterFunc;
        private static readonly ImportsGetterDelegate ImportsGetterFunc;
        private static readonly XmlNamespacesGetterDelegate XmlNamespacesGetterFunc;

        private readonly object? wrappedObject;

        static IImportScopeWrapper()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);

            AliasesGetterFunc = LightupHelper.CreateGetAccessor<AliasesGetterDelegate>(WrappedType, nameof(Aliases));
            ExternAliasesGetterFunc = LightupHelper.CreateGetAccessor<ExternAliasesGetterDelegate>(WrappedType, nameof(ExternAliases));
            ImportsGetterFunc = LightupHelper.CreateGetAccessor<ImportsGetterDelegate>(WrappedType, nameof(Imports));
            XmlNamespacesGetterFunc = LightupHelper.CreateGetAccessor<XmlNamespacesGetterDelegate>(WrappedType, nameof(XmlNamespaces));
        }

        private IImportScopeWrapper(object? obj)
        {
            wrappedObject = obj;
        }

        /// <summary>Added in Roslyn version 4.4.0.0</summary>
        public readonly ImmutableArray<IAliasSymbol> Aliases
        {
            get => AliasesGetterFunc(wrappedObject);
        }

        /// <summary>Added in Roslyn version 4.4.0.0</summary>
        public readonly ImmutableArray<IAliasSymbol> ExternAliases
        {
            get => ExternAliasesGetterFunc(wrappedObject);
        }

        /// <summary>Added in Roslyn version 4.4.0.0</summary>
        public readonly ImmutableArray<ImportedNamespaceOrTypeWrapper> Imports
        {
            get => ImportsGetterFunc(wrappedObject);
        }

        /// <summary>Added in Roslyn version 4.4.0.0</summary>
        public readonly ImmutableArray<ImportedXmlNamespaceWrapper> XmlNamespaces
        {
            get => XmlNamespacesGetterFunc(wrappedObject);
        }

        public static bool Is(object? obj)
            => LightupHelper.Is(obj, WrappedType);

        public static IImportScopeWrapper As(object? obj)
        {
            var obj2 = LightupHelper.As<object>(obj, WrappedType);
            return new IImportScopeWrapper(obj2);
        }

        public object? Unwrap()
            => wrappedObject;
    }
}
