// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Operations.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Class added in Roslyn version </summary>
    public static class LocationExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Location";

        public static readonly Type? WrappedType;

        static LocationExtensions()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);
        }
    }
}
