// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Operations.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for struct Microsoft.CodeAnalysis.NullabilityInfo. Added in version 3.8.0.0.</summary>
    public readonly struct NullabilityInfoWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.NullabilityInfo";

        private static readonly Type? WrappedType; // NOTE: Used via reflection

        private delegate NullableAnnotationEx AnnotationGetterDelegate(object? _obj);
        private delegate NullableFlowStateEx FlowStateGetterDelegate(object? _obj);

        private delegate Boolean EqualsDelegate0(object? _obj, NullabilityInfoWrapper other);

        private static readonly AnnotationGetterDelegate AnnotationGetterFunc;
        private static readonly FlowStateGetterDelegate FlowStateGetterFunc;

        private static readonly EqualsDelegate0 EqualsFunc0;

        private readonly object? wrappedObject;

        static NullabilityInfoWrapper()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);

            AnnotationGetterFunc = LightupHelper.CreateInstanceGetAccessor<AnnotationGetterDelegate>(WrappedType, nameof(Annotation));
            FlowStateGetterFunc = LightupHelper.CreateInstanceGetAccessor<FlowStateGetterDelegate>(WrappedType, nameof(FlowState));

            EqualsFunc0 = LightupHelper.CreateInstanceMethodAccessor<EqualsDelegate0>(WrappedType, nameof(Equals));
        }

        private NullabilityInfoWrapper(object? obj)
        {
            wrappedObject = obj;
        }

        /// <summary>Property added in version 3.8.0.0.</summary>
        public readonly NullableAnnotationEx Annotation
        {
            get => AnnotationGetterFunc(wrappedObject);
        }

        /// <summary>Property added in version 3.8.0.0.</summary>
        public readonly NullableFlowStateEx FlowState
        {
            get => FlowStateGetterFunc(wrappedObject);
        }

        public static bool Is(object? obj)
            => LightupHelper.Is(obj, WrappedType);

        public static NullabilityInfoWrapper As(object? obj)
        {
            var obj2 = LightupHelper.As<object>(obj, WrappedType);
            return new NullabilityInfoWrapper(obj2);
        }

        public object? Unwrap()
            => wrappedObject;

        /// <summary>Method added in version 3.8.0.0.</summary>
        public readonly Boolean Equals(NullabilityInfoWrapper other)
            => EqualsFunc0(wrappedObject, other);
    }
}
