// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for enum Microsoft.CodeAnalysis.RefKind.</summary>
    public class RefKindEx
    {
        /// <summary>Added in version 4.8.0.0.</summary>
        public const Microsoft.CodeAnalysis.RefKind RefReadOnlyParameter = (Microsoft.CodeAnalysis.RefKind)4;
    }
}
