// <auto-generated/>

#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    public class SymbolDisplayMiscellaneousOptionsEx
    {
        public const SymbolDisplayMiscellaneousOptions AllowDefaultLiteral = (SymbolDisplayMiscellaneousOptions)128;
        public const SymbolDisplayMiscellaneousOptions IncludeNotNullableReferenceTypeModifier = (SymbolDisplayMiscellaneousOptions)256;
        public const SymbolDisplayMiscellaneousOptions CollapseTupleTypes = (SymbolDisplayMiscellaneousOptions)512;
        public const SymbolDisplayMiscellaneousOptions ExpandValueTuple = (SymbolDisplayMiscellaneousOptions)1024;
    }
}
