// <auto-generated/>

#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    public class SymbolDisplayLocalOptionsEx
    {
        public const SymbolDisplayLocalOptions IncludeModifiers = (SymbolDisplayLocalOptions)4;
    }
}
