// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using Microsoft.CodeAnalysis.Lightup;

namespace Microsoft.CodeAnalysis.Emit.Lightup
{
    /// <summary>Provides lightup support for class Microsoft.CodeAnalysis.Emit.EmitDifferenceResult.</summary>
    public static class EmitDifferenceResultExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Emit.EmitDifferenceResult";

        private delegate System.Collections.Immutable.ImmutableArray<System.Reflection.Metadata.TypeDefinitionHandle> ChangedTypesGetterDelegate(Microsoft.CodeAnalysis.Emit.EmitDifferenceResult? _obj);
        private delegate System.Collections.Immutable.ImmutableArray<System.Reflection.Metadata.MethodDefinitionHandle> UpdatedMethodsGetterDelegate(Microsoft.CodeAnalysis.Emit.EmitDifferenceResult? _obj);

        private static readonly ChangedTypesGetterDelegate ChangedTypesGetterFunc;
        private static readonly UpdatedMethodsGetterDelegate UpdatedMethodsGetterFunc;

        static EmitDifferenceResultExtensions()
        {
            var wrappedType = LightupHelper.FindType(WrappedTypeName);

            ChangedTypesGetterFunc = LightupHelper.CreateInstanceGetAccessor<ChangedTypesGetterDelegate>(wrappedType, nameof(ChangedTypes));
            UpdatedMethodsGetterFunc = LightupHelper.CreateInstanceGetAccessor<UpdatedMethodsGetterDelegate>(wrappedType, nameof(UpdatedMethods));
        }

        /// <summary>Property added in version 4.0.0.0.</summary>
        public static System.Collections.Immutable.ImmutableArray<System.Reflection.Metadata.TypeDefinitionHandle> ChangedTypes(this Microsoft.CodeAnalysis.Emit.EmitDifferenceResult _obj)
            => ChangedTypesGetterFunc(_obj);

        /// <summary>Property added in version 4.0.0.0.</summary>
        public static System.Collections.Immutable.ImmutableArray<System.Reflection.Metadata.MethodDefinitionHandle> UpdatedMethods(this Microsoft.CodeAnalysis.Emit.EmitDifferenceResult _obj)
            => UpdatedMethodsGetterFunc(_obj);
    }
}
