// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Operations.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Emit.Lightup
{
    /// <summary>Provides lightup support for struct Microsoft.CodeAnalysis.Emit.SemanticEdit.</summary>
    public static class SemanticEditExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Emit.SemanticEdit";

        private delegate MethodInstrumentationWrapper InstrumentationGetterDelegate(SemanticEdit? _obj);

        private static readonly InstrumentationGetterDelegate InstrumentationGetterFunc;

        static SemanticEditExtensions()
        {
            var wrappedType = LightupHelper.FindType(WrappedTypeName);

            InstrumentationGetterFunc = LightupHelper.CreateInstanceGetAccessor<InstrumentationGetterDelegate>(wrappedType, nameof(Instrumentation));
        }

        /// <summary>Property added in version 4.8.0.0.</summary>
        public static MethodInstrumentationWrapper Instrumentation(this SemanticEdit _obj)
            => InstrumentationGetterFunc(_obj);
    }
}
