// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.CSharp.Syntax.Lightup;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.CSharp.Lightup
{
    /// <summary>Provides lightup support for class Microsoft.CodeAnalysis.CSharp.SyntaxFacts.</summary>
    public static class SyntaxFactsEx
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.SyntaxFacts";

        private delegate Boolean IsCheckedOperatorDelegate0(String operatorMetadataName);

        private static readonly IsCheckedOperatorDelegate0 IsCheckedOperatorFunc0;

        static SyntaxFactsEx()
        {
            var wrappedType = LightupHelper.FindType(WrappedTypeName);

            IsCheckedOperatorFunc0 = LightupHelper.CreateStaticMethodAccessor<IsCheckedOperatorDelegate0>(wrappedType, nameof(IsCheckedOperator));
        }

        /// <summary>Method added in version 4.4.0.0.</summary>
        public static Boolean IsCheckedOperator(String operatorMetadataName)
            => IsCheckedOperatorFunc0(operatorMetadataName);
    }
}
