// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Diagnostics.Lightup
{
    /// <summary>Class added in Roslyn version </summary>
    public static class AnalyzerOptionsExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Diagnostics.AnalyzerOptions";

        public static readonly Type? WrappedType;

        private delegate AnalyzerConfigOptionsProviderWrapper AnalyzerConfigOptionsProviderGetterDelegate(AnalyzerOptions? _obj);

        private static readonly AnalyzerConfigOptionsProviderGetterDelegate AnalyzerConfigOptionsProviderGetterFunc;

        static AnalyzerOptionsExtensions()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);

            AnalyzerConfigOptionsProviderGetterFunc = LightupHelper.CreateGetAccessor<AnalyzerConfigOptionsProviderGetterDelegate>(WrappedType, nameof(AnalyzerConfigOptionsProvider));
        }

        /// <summary>Added in Roslyn version 3.8.0.0</summary>
        public static AnalyzerConfigOptionsProviderWrapper AnalyzerConfigOptionsProvider(this AnalyzerOptions _obj)
            => AnalyzerConfigOptionsProviderGetterFunc(_obj);
    }
}
