// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Operations.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Diagnostics.Lightup
{
    /// <summary>Provides lightup support for class Microsoft.CodeAnalysis.Diagnostics.OperationBlockStartAnalysisContext.</summary>
    public static class OperationBlockStartAnalysisContextExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Diagnostics.OperationBlockStartAnalysisContext";

        private delegate Nullable<TextSpan> FilterSpanGetterDelegate(OperationBlockStartAnalysisContext? _obj);
        private delegate SyntaxTree FilterTreeGetterDelegate(OperationBlockStartAnalysisContext? _obj);
        private delegate Boolean IsGeneratedCodeGetterDelegate(OperationBlockStartAnalysisContext? _obj);

        private static readonly FilterSpanGetterDelegate FilterSpanGetterFunc;
        private static readonly FilterTreeGetterDelegate FilterTreeGetterFunc;
        private static readonly IsGeneratedCodeGetterDelegate IsGeneratedCodeGetterFunc;

        static OperationBlockStartAnalysisContextExtensions()
        {
            var wrappedType = LightupHelper.FindType(WrappedTypeName);

            FilterSpanGetterFunc = LightupHelper.CreateInstanceGetAccessor<FilterSpanGetterDelegate>(wrappedType, nameof(FilterSpan));
            FilterTreeGetterFunc = LightupHelper.CreateInstanceGetAccessor<FilterTreeGetterDelegate>(wrappedType, nameof(FilterTree));
            IsGeneratedCodeGetterFunc = LightupHelper.CreateInstanceGetAccessor<IsGeneratedCodeGetterDelegate>(wrappedType, nameof(IsGeneratedCode));
        }

        /// <summary>Property added in version 4.8.0.0.</summary>
        public static Nullable<TextSpan> FilterSpan(this OperationBlockStartAnalysisContext _obj)
            => FilterSpanGetterFunc(_obj);

        /// <summary>Property added in version 4.8.0.0.</summary>
        public static SyntaxTree FilterTree(this OperationBlockStartAnalysisContext _obj)
            => FilterTreeGetterFunc(_obj);

        /// <summary>Property added in version 4.4.0.0.</summary>
        public static Boolean IsGeneratedCode(this OperationBlockStartAnalysisContext _obj)
            => IsGeneratedCodeGetterFunc(_obj);
    }
}
