// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using Microsoft.CodeAnalysis.Lightup;

namespace Microsoft.CodeAnalysis.Diagnostics.Lightup
{
    /// <summary>Provides lightup support for struct Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext.</summary>
    public static partial class OperationAnalysisContextExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext";

        private delegate System.Nullable<Microsoft.CodeAnalysis.Text.TextSpan> FilterSpanGetterDelegate(Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext? _obj);
        private delegate Microsoft.CodeAnalysis.SyntaxTree FilterTreeGetterDelegate(Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext? _obj);
        private delegate System.Boolean IsGeneratedCodeGetterDelegate(Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext? _obj);

        private static readonly FilterSpanGetterDelegate FilterSpanGetterFunc;
        private static readonly FilterTreeGetterDelegate FilterTreeGetterFunc;
        private static readonly IsGeneratedCodeGetterDelegate IsGeneratedCodeGetterFunc;

        static OperationAnalysisContextExtensions()
        {
            var wrappedType = CommonLightupHelper.FindType(WrappedTypeName);

            FilterSpanGetterFunc = CommonLightupHelper.CreateInstanceGetAccessor<FilterSpanGetterDelegate>(wrappedType, nameof(FilterSpan));
            FilterTreeGetterFunc = CommonLightupHelper.CreateInstanceGetAccessor<FilterTreeGetterDelegate>(wrappedType, nameof(FilterTree));
            IsGeneratedCodeGetterFunc = CommonLightupHelper.CreateInstanceGetAccessor<IsGeneratedCodeGetterDelegate>(wrappedType, nameof(IsGeneratedCode));
        }

        /// <summary>Property added in version 4.8.0.0.</summary>
        public static System.Nullable<Microsoft.CodeAnalysis.Text.TextSpan> FilterSpan(this Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext _obj)
            => FilterSpanGetterFunc(_obj);

        /// <summary>Property added in version 4.8.0.0.</summary>
        public static Microsoft.CodeAnalysis.SyntaxTree FilterTree(this Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext _obj)
            => FilterTreeGetterFunc(_obj);

        /// <summary>Property added in version 4.4.0.0.</summary>
        public static System.Boolean IsGeneratedCode(this Microsoft.CodeAnalysis.Diagnostics.OperationAnalysisContext _obj)
            => IsGeneratedCodeGetterFunc(_obj);
    }
}
