// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Operations.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Diagnostics.Lightup
{
    public static class SemanticModelAnalysisContextExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Diagnostics.SemanticModelAnalysisContext";

        public static readonly Type? WrappedType;

        private delegate Nullable<TextSpan> FilterSpanGetterDelegate(SemanticModelAnalysisContext? _obj);
        private delegate SyntaxTree FilterTreeGetterDelegate(SemanticModelAnalysisContext? _obj);
        private delegate Boolean IsGeneratedCodeGetterDelegate(SemanticModelAnalysisContext? _obj);

        private static readonly FilterSpanGetterDelegate FilterSpanGetterFunc;
        private static readonly FilterTreeGetterDelegate FilterTreeGetterFunc;
        private static readonly IsGeneratedCodeGetterDelegate IsGeneratedCodeGetterFunc;

        static SemanticModelAnalysisContextExtensions()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);

            FilterSpanGetterFunc = LightupHelper.CreateInstanceGetAccessor<FilterSpanGetterDelegate>(WrappedType, nameof(FilterSpan));
            FilterTreeGetterFunc = LightupHelper.CreateInstanceGetAccessor<FilterTreeGetterDelegate>(WrappedType, nameof(FilterTree));
            IsGeneratedCodeGetterFunc = LightupHelper.CreateInstanceGetAccessor<IsGeneratedCodeGetterDelegate>(WrappedType, nameof(IsGeneratedCode));
        }

        /// <summary>Added in Roslyn version 4.8.0.0</summary>
        public static Nullable<TextSpan> FilterSpan(this SemanticModelAnalysisContext _obj)
            => FilterSpanGetterFunc(_obj);

        /// <summary>Added in Roslyn version 4.8.0.0</summary>
        public static SyntaxTree FilterTree(this SemanticModelAnalysisContext _obj)
            => FilterTreeGetterFunc(_obj);

        /// <summary>Added in Roslyn version 4.4.0.0</summary>
        public static Boolean IsGeneratedCode(this SemanticModelAnalysisContext _obj)
            => IsGeneratedCodeGetterFunc(_obj);
    }
}
