// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Operations.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Operations.Lightup
{
    public static class IForEachLoopOperationExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.IForEachLoopOperation";

        private static readonly Type? WrappedType; // NOTE: Used via reflection

        private delegate Boolean IsAsynchronousGetterDelegate(IForEachLoopOperation? _obj);

        private static readonly IsAsynchronousGetterDelegate IsAsynchronousGetterFunc;

        static IForEachLoopOperationExtensions()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);

            IsAsynchronousGetterFunc = LightupHelper.CreateInstanceGetAccessor<IsAsynchronousGetterDelegate>(WrappedType, nameof(IsAsynchronous));
        }

        /// <summary>Property added in version 3.8.0.0 of Roslyn.</summary>
        public static Boolean IsAsynchronous(this IForEachLoopOperation _obj)
            => IsAsynchronousGetterFunc(_obj);
    }
}
