// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Operations.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Operations.Lightup
{
    /// <summary>Interface added in version 4.4.0.0 of Roslyn.</summary>
    public readonly struct IInterpolatedStringHandlerCreationOperationWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.IInterpolatedStringHandlerCreationOperation";

        private static readonly Type? WrappedType; // NOTE: Used via reflection

        private delegate IOperation ContentGetterDelegate(IOperation? _obj);
        private delegate Boolean HandlerAppendCallsReturnBoolGetterDelegate(IOperation? _obj);
        private delegate IOperation HandlerCreationGetterDelegate(IOperation? _obj);
        private delegate Boolean HandlerCreationHasSuccessParameterGetterDelegate(IOperation? _obj);

        private static readonly ContentGetterDelegate ContentGetterFunc;
        private static readonly HandlerAppendCallsReturnBoolGetterDelegate HandlerAppendCallsReturnBoolGetterFunc;
        private static readonly HandlerCreationGetterDelegate HandlerCreationGetterFunc;
        private static readonly HandlerCreationHasSuccessParameterGetterDelegate HandlerCreationHasSuccessParameterGetterFunc;

        private readonly IOperation? wrappedObject;

        static IInterpolatedStringHandlerCreationOperationWrapper()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);

            ContentGetterFunc = LightupHelper.CreateInstanceGetAccessor<ContentGetterDelegate>(WrappedType, nameof(Content));
            HandlerAppendCallsReturnBoolGetterFunc = LightupHelper.CreateInstanceGetAccessor<HandlerAppendCallsReturnBoolGetterDelegate>(WrappedType, nameof(HandlerAppendCallsReturnBool));
            HandlerCreationGetterFunc = LightupHelper.CreateInstanceGetAccessor<HandlerCreationGetterDelegate>(WrappedType, nameof(HandlerCreation));
            HandlerCreationHasSuccessParameterGetterFunc = LightupHelper.CreateInstanceGetAccessor<HandlerCreationHasSuccessParameterGetterDelegate>(WrappedType, nameof(HandlerCreationHasSuccessParameter));
        }

        private IInterpolatedStringHandlerCreationOperationWrapper(IOperation? obj)
        {
            wrappedObject = obj;
        }

        /// <summary>Property added in version 4.4.0.0 of Roslyn.</summary>
        public readonly IOperation Content
        {
            get => ContentGetterFunc(wrappedObject);
        }

        /// <summary>Property added in version 4.4.0.0 of Roslyn.</summary>
        public readonly Boolean HandlerAppendCallsReturnBool
        {
            get => HandlerAppendCallsReturnBoolGetterFunc(wrappedObject);
        }

        /// <summary>Property added in version 4.4.0.0 of Roslyn.</summary>
        public readonly IOperation HandlerCreation
        {
            get => HandlerCreationGetterFunc(wrappedObject);
        }

        /// <summary>Property added in version 4.4.0.0 of Roslyn.</summary>
        public readonly Boolean HandlerCreationHasSuccessParameter
        {
            get => HandlerCreationHasSuccessParameterGetterFunc(wrappedObject);
        }

        public static bool Is(object? obj)
            => LightupHelper.Is(obj, WrappedType);

        public static IInterpolatedStringHandlerCreationOperationWrapper As(object? obj)
        {
            var obj2 = LightupHelper.As<IOperation>(obj, WrappedType);
            return new IInterpolatedStringHandlerCreationOperationWrapper(obj2);
        }

        public IOperation? Unwrap()
            => wrappedObject;
    }
}
