
// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    internal class CommonLightupHelper : Roslyn.CodeAnalysis.Lightup.Runtime.LightupHelper
    {
        private static readonly System.Reflection.Assembly Assembly = typeof(Microsoft.CodeAnalysis.IOperation).Assembly;

        public static System.Type? FindType(string wrappedTypeName)
        {
            return FindType(Assembly, wrappedTypeName);
        }
    }
}
