// <auto-generated/>
#nullable enable

using Microsoft.CodeAnalysis.Lightup;

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for class Microsoft.CodeAnalysis.DataFlowAnalysis.</summary>
    public static partial class DataFlowAnalysisExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.DataFlowAnalysis";

        private delegate System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.ISymbol> DefinitelyAssignedOnEntryGetterDelegate(Microsoft.CodeAnalysis.DataFlowAnalysis? _obj);
        private delegate System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.ISymbol> DefinitelyAssignedOnExitGetterDelegate(Microsoft.CodeAnalysis.DataFlowAnalysis? _obj);
        private delegate System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.IMethodSymbol> UsedLocalFunctionsGetterDelegate(Microsoft.CodeAnalysis.DataFlowAnalysis? _obj);

        private static readonly DefinitelyAssignedOnEntryGetterDelegate DefinitelyAssignedOnEntryGetterFunc;
        private static readonly DefinitelyAssignedOnExitGetterDelegate DefinitelyAssignedOnExitGetterFunc;
        private static readonly UsedLocalFunctionsGetterDelegate UsedLocalFunctionsGetterFunc;

        static DataFlowAnalysisExtensions()
        {
            var wrappedType = CommonLightupHelper.FindType(WrappedTypeName);

            DefinitelyAssignedOnEntryGetterFunc = CommonLightupHelper.CreateInstanceGetAccessor<DefinitelyAssignedOnEntryGetterDelegate>(wrappedType, nameof(DefinitelyAssignedOnEntry));
            DefinitelyAssignedOnExitGetterFunc = CommonLightupHelper.CreateInstanceGetAccessor<DefinitelyAssignedOnExitGetterDelegate>(wrappedType, nameof(DefinitelyAssignedOnExit));
            UsedLocalFunctionsGetterFunc = CommonLightupHelper.CreateInstanceGetAccessor<UsedLocalFunctionsGetterDelegate>(wrappedType, nameof(UsedLocalFunctions));
        }

        /// <summary>Property added in version 3.8.0.0.</summary>
        public static System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.ISymbol> DefinitelyAssignedOnEntry(this Microsoft.CodeAnalysis.DataFlowAnalysis _obj)
            => DefinitelyAssignedOnEntryGetterFunc(_obj);

        /// <summary>Property added in version 3.8.0.0.</summary>
        public static System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.ISymbol> DefinitelyAssignedOnExit(this Microsoft.CodeAnalysis.DataFlowAnalysis _obj)
            => DefinitelyAssignedOnExitGetterFunc(_obj);

        /// <summary>Property added in version 3.8.0.0.</summary>
        public static System.Collections.Immutable.ImmutableArray<Microsoft.CodeAnalysis.IMethodSymbol> UsedLocalFunctions(this Microsoft.CodeAnalysis.DataFlowAnalysis _obj)
            => UsedLocalFunctionsGetterFunc(_obj);
    }
}
