// <auto-generated/>
#nullable enable

using Microsoft.CodeAnalysis.Lightup;

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for class Microsoft.CodeAnalysis.ErrorLogOptions. Added in version 3.8.0.0.</summary>
    public readonly partial struct ErrorLogOptionsWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.ErrorLogOptions";

        private static readonly System.Type? WrappedType; // NOTE: Used via reflection

        private delegate ErrorLogOptionsWrapper ConstructorDelegate0(System.String path, Microsoft.CodeAnalysis.Lightup.SarifVersionEx sarifVersion);

        private delegate System.String PathGetterDelegate(System.Object? _obj);
        private delegate Microsoft.CodeAnalysis.Lightup.SarifVersionEx SarifVersionGetterDelegate(System.Object? _obj);

        private static readonly ConstructorDelegate0 ConstructorFunc0;

        private static readonly PathGetterDelegate PathGetterFunc;
        private static readonly SarifVersionGetterDelegate SarifVersionGetterFunc;

        private readonly System.Object? wrappedObject;

        static ErrorLogOptionsWrapper()
        {
            WrappedType = CommonLightupHelper.FindType(WrappedTypeName);

            ConstructorFunc0 = CommonLightupHelper.CreateInstanceConstructorAccessor<ConstructorDelegate0>(WrappedType, "pathString", "sarifVersionSarifVersion");

            PathGetterFunc = CommonLightupHelper.CreateInstanceGetAccessor<PathGetterDelegate>(WrappedType, nameof(Path));
            SarifVersionGetterFunc = CommonLightupHelper.CreateInstanceGetAccessor<SarifVersionGetterDelegate>(WrappedType, nameof(SarifVersion));
        }

        private ErrorLogOptionsWrapper(System.Object? obj)
        {
            wrappedObject = obj;
        }

        /// <summary>Constructor added in version 3.8.0.0.</summary>
        public static ErrorLogOptionsWrapper Create(System.String path, Microsoft.CodeAnalysis.Lightup.SarifVersionEx sarifVersion)
            => ConstructorFunc0(path, sarifVersion);

        /// <summary>Property added in version 3.8.0.0.</summary>
        public readonly System.String Path
        {
            get => PathGetterFunc(wrappedObject);
        }

        /// <summary>Property added in version 3.8.0.0.</summary>
        public readonly Microsoft.CodeAnalysis.Lightup.SarifVersionEx SarifVersion
        {
            get => SarifVersionGetterFunc(wrappedObject);
        }

        /// <summary>Returns true if the specified object is compatible with this wrapper.</summary>
        public static bool Is(System.Object? obj)
            => CommonLightupHelper.Is(obj, WrappedType);

        /// <summary>Creates a wrapper object containing the specified object. If the object is not compatible with this wrapper, null will be stored in the wrapper instead.</summary>
        public static ErrorLogOptionsWrapper As(System.Object? obj)
        {
            var obj2 = CommonLightupHelper.As<System.Object>(obj, WrappedType);
            return new ErrorLogOptionsWrapper(obj2);
        }

        /// <summary>Returns the wrapped object.</summary>
        public System.Object? Unwrap()
            => wrappedObject;
    }
}
