// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for enum Microsoft.CodeAnalysis.SymbolDisplayParameterOptions.</summary>
    public static partial class SymbolDisplayParameterOptionsEx
    {
        /// <summary>Added in version 4.8.0.0.</summary>
        public const Microsoft.CodeAnalysis.SymbolDisplayParameterOptions IncludeModifiers = (Microsoft.CodeAnalysis.SymbolDisplayParameterOptions)2;
    }
}
