// <auto-generated/>

#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    public class ApplyChangesKindEx
    {
        public const ApplyChangesKind AddAnalyzerConfigDocument = (ApplyChangesKind)17;
        public const ApplyChangesKind RemoveAnalyzerConfigDocument = (ApplyChangesKind)18;
        public const ApplyChangesKind ChangeAnalyzerConfigDocument = (ApplyChangesKind)19;
        public const ApplyChangesKind AddSolutionAnalyzerReference = (ApplyChangesKind)20;
        public const ApplyChangesKind RemoveSolutionAnalyzerReference = (ApplyChangesKind)21;
    }
}
