// Copyright © Björn Hellander 2024
// Licensed under the MIT License. See LICENSE.txt in the repository root for license information.

// <auto-generated/>

#nullable enable

using Microsoft.CodeAnalysis.Lightup;

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for struct Microsoft.CodeAnalysis.LoadTextOptions. Added in version 4.8.0.0.</summary>
    public readonly struct LoadTextOptionsWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.LoadTextOptions";

        private static readonly System.Type? WrappedType; // NOTE: Used via reflection

        private delegate LoadTextOptionsWrapper ConstructorDelegate0(Microsoft.CodeAnalysis.Text.SourceHashAlgorithm checksumAlgorithm);

        private delegate Microsoft.CodeAnalysis.Text.SourceHashAlgorithm ChecksumAlgorithmGetterDelegate(System.Object? _obj);

        private delegate System.Boolean EqualsDelegate0(System.Object? _obj, Microsoft.CodeAnalysis.Lightup.LoadTextOptionsWrapper other);

        private static readonly ConstructorDelegate0 ConstructorFunc0;

        private static readonly ChecksumAlgorithmGetterDelegate ChecksumAlgorithmGetterFunc;

        private static readonly EqualsDelegate0 EqualsFunc0;

        private readonly System.Object? wrappedObject;

        static LoadTextOptionsWrapper()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);

            ConstructorFunc0 = LightupHelper.CreateInstanceConstructorAccessor<ConstructorDelegate0>(WrappedType, "checksumAlgorithmSourceHashAlgorithm");

            ChecksumAlgorithmGetterFunc = LightupHelper.CreateInstanceGetAccessor<ChecksumAlgorithmGetterDelegate>(WrappedType, nameof(ChecksumAlgorithm));

            EqualsFunc0 = LightupHelper.CreateInstanceMethodAccessor<EqualsDelegate0>(WrappedType, "Equals", "otherLoadTextOptions");
        }

        private LoadTextOptionsWrapper(System.Object? obj)
        {
            wrappedObject = obj;
        }

        /// <summary>Constructor added in version 4.8.0.0.</summary>
        public static LoadTextOptionsWrapper Create(Microsoft.CodeAnalysis.Text.SourceHashAlgorithm checksumAlgorithm)
            => ConstructorFunc0(checksumAlgorithm);

        /// <summary>Property added in version 4.8.0.0.</summary>
        public readonly Microsoft.CodeAnalysis.Text.SourceHashAlgorithm ChecksumAlgorithm
        {
            get => ChecksumAlgorithmGetterFunc(wrappedObject);
        }

        public static bool Is(System.Object? obj)
            => LightupHelper.Is(obj, WrappedType);

        public static LoadTextOptionsWrapper As(System.Object? obj)
        {
            var obj2 = LightupHelper.As<System.Object>(obj, WrappedType);
            return new LoadTextOptionsWrapper(obj2);
        }

        public System.Object? Unwrap()
            => wrappedObject;

        /// <summary>Method added in version 4.8.0.0.</summary>
        public readonly System.Boolean Equals(Microsoft.CodeAnalysis.Lightup.LoadTextOptionsWrapper other)
            => EqualsFunc0(wrappedObject, other);
    }
}
