// <auto-generated/>

#nullable enable

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Reflection.Metadata;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeActions.Lightup;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Host;
using Microsoft.CodeAnalysis.Host.Lightup;
using Microsoft.CodeAnalysis.Lightup;
using Microsoft.CodeAnalysis.Text;

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Class added in Roslyn version </summary>
    public static class WorkspaceRegistrationExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.WorkspaceRegistration";

        public static readonly Type? WrappedType;

        static WorkspaceRegistrationExtensions()
        {
            WrappedType = LightupHelper.FindType(WrappedTypeName);
        }
    }
}
