// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Operations.Lightup
{
    /// <summary>Provides lightup support for interface Microsoft.CodeAnalysis.Operations.IMethodReferenceOperation. Added in version 2.6.0.0.</summary>
    public partial struct IMethodReferenceOperationWrapper
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.IMethodReferenceOperation";

        private static readonly global::System.Type? WrappedType; // NOTE: Used via reflection

        private delegate global::System.Boolean IsVirtualGetterDelegate(global::Microsoft.CodeAnalysis.Operations.IMemberReferenceOperation? _obj);
        private delegate global::Microsoft.CodeAnalysis.IMethodSymbol MethodGetterDelegate(global::Microsoft.CodeAnalysis.Operations.IMemberReferenceOperation? _obj);

        private static readonly IsVirtualGetterDelegate IsVirtualGetterFunc;
        private static readonly MethodGetterDelegate MethodGetterFunc;

        private readonly global::Microsoft.CodeAnalysis.Operations.IMemberReferenceOperation? wrappedObject;

        static IMethodReferenceOperationWrapper()
        {
            WrappedType = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.FindType(WrappedTypeName);

            IsVirtualGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<IsVirtualGetterDelegate>(WrappedType, nameof(IsVirtual));
            MethodGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<MethodGetterDelegate>(WrappedType, nameof(Method));
        }

        private IMethodReferenceOperationWrapper(global::Microsoft.CodeAnalysis.Operations.IMemberReferenceOperation? obj)
        {
            wrappedObject = obj;
        }

        /// <summary>Property added in version 2.6.0.0.</summary>
        public global::System.Boolean IsVirtual
        {
            get { return IsVirtualGetterFunc(wrappedObject); }
        }

        /// <summary>Property added in version 2.6.0.0.</summary>
        public global::Microsoft.CodeAnalysis.IMethodSymbol Method
        {
            get { return MethodGetterFunc(wrappedObject); }
        }

        /// <summary>Returns true if the specified object is compatible with this wrapper.</summary>
        public static bool Is(global::System.Object? obj)
        {
            return global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.Is(obj, WrappedType);
        }

        /// <summary>Creates a wrapper object containing the specified object. If the object is not compatible with this wrapper, null will be stored in the wrapper instead.</summary>
        public static IMethodReferenceOperationWrapper As(global::System.Object? obj)
        {
            var obj2 = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.As<global::Microsoft.CodeAnalysis.Operations.IMemberReferenceOperation>(obj, WrappedType);
            return new IMethodReferenceOperationWrapper(obj2);
        }

        /// <summary>Returns the wrapped object.</summary>
        public global::Microsoft.CodeAnalysis.Operations.IMemberReferenceOperation? Unwrap()
        {
            return wrappedObject;
        }
    }
}
