// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Operations.Lightup
{
    /// <summary>Provides lightup support for interface Microsoft.CodeAnalysis.Operations.ISwitchOperation.</summary>
    public static partial class ISwitchOperationEx
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.ISwitchOperation";

        private delegate global::Microsoft.CodeAnalysis.ILabelSymbol ExitLabelGetterDelegate(global::Microsoft.CodeAnalysis.Operations.ISwitchOperation _obj);
        private delegate global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.ILocalSymbol> LocalsGetterDelegate(global::Microsoft.CodeAnalysis.Operations.ISwitchOperation _obj);

        private static readonly ExitLabelGetterDelegate ExitLabelGetterFunc;
        private static readonly LocalsGetterDelegate LocalsGetterFunc;

        static ISwitchOperationEx()
        {
            var wrappedType = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.FindType(WrappedTypeName);

            ExitLabelGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<ExitLabelGetterDelegate>(wrappedType, nameof(ExitLabel));
            LocalsGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<LocalsGetterDelegate>(wrappedType, nameof(Locals));
        }

        /// <summary>Property added in version 2.9.0.0.</summary>
        public static global::Microsoft.CodeAnalysis.ILabelSymbol ExitLabel(this global::Microsoft.CodeAnalysis.Operations.ISwitchOperation _obj)
        {
            return ExitLabelGetterFunc(_obj);
        }

        /// <summary>Property added in version 2.9.0.0.</summary>
        public static global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.ILocalSymbol> Locals(this global::Microsoft.CodeAnalysis.Operations.ISwitchOperation _obj)
        {
            return LocalsGetterFunc(_obj);
        }
    }
}
