// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Operations.Lightup
{
    /// <summary>Provides lightup support for interface Microsoft.CodeAnalysis.Operations.IVariableDeclarationOperation.</summary>
    public static partial class IVariableDeclarationOperationExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.Operations.IVariableDeclarationOperation";

        private delegate global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.IOperation> IgnoredDimensionsGetterDelegate(global::Microsoft.CodeAnalysis.Operations.IVariableDeclarationOperation? _obj);

        private static readonly IgnoredDimensionsGetterDelegate IgnoredDimensionsGetterFunc;

        static IVariableDeclarationOperationExtensions()
        {
            var wrappedType = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.FindType(WrappedTypeName);

            IgnoredDimensionsGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateInstanceGetAccessor<IgnoredDimensionsGetterDelegate>(wrappedType, nameof(IgnoredDimensions));
        }

        /// <summary>Property added in version 3.8.0.0.</summary>
        public static global::System.Collections.Immutable.ImmutableArray<global::Microsoft.CodeAnalysis.IOperation> IgnoredDimensions(this global::Microsoft.CodeAnalysis.Operations.IVariableDeclarationOperation _obj)
        {
            return IgnoredDimensionsGetterFunc(_obj);
        }
    }
}
