// <auto-generated/>
#nullable enable

using Microsoft.CodeAnalysis.Lightup;

namespace Microsoft.CodeAnalysis.CSharp.Lightup
{
    /// <summary>Provides lightup support for class Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions.</summary>
    public static partial class CSharpCompilationOptionsExtensions
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions";

        private delegate CSharpCompilationOptions ConstructorDelegate0(Microsoft.CodeAnalysis.OutputKind outputKind, System.Boolean reportSuppressedDiagnostics, System.String? moduleName, System.String? mainTypeName, System.String? scriptClassName, System.Collections.Generic.IEnumerable<System.String>? usings, Microsoft.CodeAnalysis.OptimizationLevel optimizationLevel, System.Boolean checkOverflow, System.Boolean allowUnsafe, System.String? cryptoKeyContainer, System.String? cryptoKeyFile, System.Collections.Immutable.ImmutableArray<System.Byte> cryptoPublicKey, System.Nullable<System.Boolean> delaySign, Microsoft.CodeAnalysis.Platform platform, Microsoft.CodeAnalysis.ReportDiagnostic generalDiagnosticOption, System.Int32 warningLevel, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, Microsoft.CodeAnalysis.ReportDiagnostic>>? specificDiagnosticOptions, System.Boolean concurrentBuild, System.Boolean deterministic, Microsoft.CodeAnalysis.XmlReferenceResolver? xmlReferenceResolver, Microsoft.CodeAnalysis.SourceReferenceResolver? sourceReferenceResolver, Microsoft.CodeAnalysis.MetadataReferenceResolver? metadataReferenceResolver, Microsoft.CodeAnalysis.AssemblyIdentityComparer? assemblyIdentityComparer, Microsoft.CodeAnalysis.StrongNameProvider? strongNameProvider, System.Boolean publicSign, Microsoft.CodeAnalysis.MetadataImportOptions metadataImportOptions, Microsoft.CodeAnalysis.Lightup.NullableContextOptionsEx nullableContextOptions);

        private delegate Microsoft.CodeAnalysis.Lightup.NullableContextOptionsEx NullableContextOptionsGetterDelegate(Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions? _obj);

        private delegate Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions WithNullableContextOptionsDelegate0(Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions? _obj, Microsoft.CodeAnalysis.Lightup.NullableContextOptionsEx options);
        private delegate Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions WithSyntaxTreeOptionsProviderDelegate1(Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions? _obj, Microsoft.CodeAnalysis.Lightup.SyntaxTreeOptionsProviderWrapper provider);

        private static readonly ConstructorDelegate0 ConstructorFunc0;

        private static readonly NullableContextOptionsGetterDelegate NullableContextOptionsGetterFunc;

        private static readonly WithNullableContextOptionsDelegate0 WithNullableContextOptionsFunc0;
        private static readonly WithSyntaxTreeOptionsProviderDelegate1 WithSyntaxTreeOptionsProviderFunc1;

        static CSharpCompilationOptionsExtensions()
        {
            var wrappedType = CSharpLightupHelper.FindType(WrappedTypeName);

            ConstructorFunc0 = CSharpLightupHelper.CreateInstanceConstructorAccessor<ConstructorDelegate0>(wrappedType, "outputKindOutputKind", "reportSuppressedDiagnosticsBoolean", "moduleNameString", "mainTypeNameString", "scriptClassNameString", "usingsIEnumerable`1", "optimizationLevelOptimizationLevel", "checkOverflowBoolean", "allowUnsafeBoolean", "cryptoKeyContainerString", "cryptoKeyFileString", "cryptoPublicKeyImmutableArray`1", "delaySignNullable`1", "platformPlatform", "generalDiagnosticOptionReportDiagnostic", "warningLevelInt32", "specificDiagnosticOptionsIEnumerable`1", "concurrentBuildBoolean", "deterministicBoolean", "xmlReferenceResolverXmlReferenceResolver", "sourceReferenceResolverSourceReferenceResolver", "metadataReferenceResolverMetadataReferenceResolver", "assemblyIdentityComparerAssemblyIdentityComparer", "strongNameProviderStrongNameProvider", "publicSignBoolean", "metadataImportOptionsMetadataImportOptions", "nullableContextOptionsNullableContextOptions");

            NullableContextOptionsGetterFunc = CSharpLightupHelper.CreateInstanceGetAccessor<NullableContextOptionsGetterDelegate>(wrappedType, nameof(NullableContextOptions));

            WithNullableContextOptionsFunc0 = CSharpLightupHelper.CreateInstanceMethodAccessor<WithNullableContextOptionsDelegate0>(wrappedType, "WithNullableContextOptions", "optionsNullableContextOptions");
            WithSyntaxTreeOptionsProviderFunc1 = CSharpLightupHelper.CreateInstanceMethodAccessor<WithSyntaxTreeOptionsProviderDelegate1>(wrappedType, "WithSyntaxTreeOptionsProvider", "providerSyntaxTreeOptionsProvider");
        }

        /// <summary>Constructor added in version 3.8.0.0.</summary>
        public static CSharpCompilationOptions Create(Microsoft.CodeAnalysis.OutputKind outputKind, System.Boolean reportSuppressedDiagnostics, System.String? moduleName, System.String? mainTypeName, System.String? scriptClassName, System.Collections.Generic.IEnumerable<System.String>? usings, Microsoft.CodeAnalysis.OptimizationLevel optimizationLevel, System.Boolean checkOverflow, System.Boolean allowUnsafe, System.String? cryptoKeyContainer, System.String? cryptoKeyFile, System.Collections.Immutable.ImmutableArray<System.Byte> cryptoPublicKey, System.Nullable<System.Boolean> delaySign, Microsoft.CodeAnalysis.Platform platform, Microsoft.CodeAnalysis.ReportDiagnostic generalDiagnosticOption, System.Int32 warningLevel, System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<System.String, Microsoft.CodeAnalysis.ReportDiagnostic>>? specificDiagnosticOptions, System.Boolean concurrentBuild, System.Boolean deterministic, Microsoft.CodeAnalysis.XmlReferenceResolver? xmlReferenceResolver, Microsoft.CodeAnalysis.SourceReferenceResolver? sourceReferenceResolver, Microsoft.CodeAnalysis.MetadataReferenceResolver? metadataReferenceResolver, Microsoft.CodeAnalysis.AssemblyIdentityComparer? assemblyIdentityComparer, Microsoft.CodeAnalysis.StrongNameProvider? strongNameProvider, System.Boolean publicSign, Microsoft.CodeAnalysis.MetadataImportOptions metadataImportOptions, Microsoft.CodeAnalysis.Lightup.NullableContextOptionsEx nullableContextOptions)
            => ConstructorFunc0(outputKind, reportSuppressedDiagnostics, moduleName, mainTypeName, scriptClassName, usings, optimizationLevel, checkOverflow, allowUnsafe, cryptoKeyContainer, cryptoKeyFile, cryptoPublicKey, delaySign, platform, generalDiagnosticOption, warningLevel, specificDiagnosticOptions, concurrentBuild, deterministic, xmlReferenceResolver, sourceReferenceResolver, metadataReferenceResolver, assemblyIdentityComparer, strongNameProvider, publicSign, metadataImportOptions, nullableContextOptions);

        /// <summary>Property added in version 3.8.0.0.</summary>
        public static Microsoft.CodeAnalysis.Lightup.NullableContextOptionsEx NullableContextOptions(this Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions _obj)
            => NullableContextOptionsGetterFunc(_obj);

        /// <summary>Method added in version 3.8.0.0.</summary>
        public static Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions WithNullableContextOptions(this Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions _obj, Microsoft.CodeAnalysis.Lightup.NullableContextOptionsEx options)
            => WithNullableContextOptionsFunc0(_obj, options);

        /// <summary>Method added in version 3.8.0.0.</summary>
        public static Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions WithSyntaxTreeOptionsProvider(this Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions _obj, Microsoft.CodeAnalysis.Lightup.SyntaxTreeOptionsProviderWrapper provider)
            => WithSyntaxTreeOptionsProviderFunc1(_obj, provider);
    }
}
