
// <auto-generated/>
#pragma warning disable CS1591
#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    // TODO: Implement remaining members
    public struct SeparatedSyntaxListWrapper<TNode>
    {
        private static readonly global::System.Type? WrappedType; // NOTE: Possibly used via reflection

        private delegate int CountDelegate(object? obj);
        private delegate SeparatedSyntaxListWrapper<TNode> AddRangeDelegate(object? obj, global::System.Collections.Generic.IEnumerable<TNode> arg1);

        private static readonly CountDelegate CountAccessor;
        private static readonly AddRangeDelegate AddRangeAccessor;

        private readonly object? wrappedObject;

        static SeparatedSyntaxListWrapper()
        {
            var wrapperNodeType = typeof(TNode);
            var wrappedNodeTypeField = wrapperNodeType.GetField("WrappedType", global::System.Reflection.BindingFlags.Static | global::System.Reflection.BindingFlags.NonPublic);
            var wrappedNodeType = (global::System.Type)wrappedNodeTypeField.GetValue(null);
            WrappedType = wrappedNodeType != null ? typeof(SeparatedSyntaxList<>).MakeGenericType(wrappedNodeType) : null;

            CountAccessor = global::Microsoft.CodeAnalysis.Lightup.CSharpLightupHelper.CreateInstanceGetAccessor<CountDelegate>(WrappedType, nameof(Count));
            AddRangeAccessor = global::Microsoft.CodeAnalysis.Lightup.CSharpLightupHelper.CreateInstanceMethodAccessor<AddRangeDelegate>(WrappedType, nameof(AddRange), "nodesIEnumerable`1");
        }

        private SeparatedSyntaxListWrapper(object? obj)
        {
            wrappedObject = obj;
        }

        public readonly int Count
            => CountAccessor(wrappedObject);

        public readonly int SeparatorCount
            => throw new global::System.NotImplementedException();

        public readonly global::Microsoft.CodeAnalysis.Text.TextSpan FullSpan
            => throw new global::System.NotImplementedException();

        public readonly global::Microsoft.CodeAnalysis.Text.TextSpan Span
            => throw new global::System.NotImplementedException();

        public readonly TNode this[int index]
            => throw new global::System.NotImplementedException();

        public static implicit operator SeparatedSyntaxListWrapper<SyntaxNode>(SeparatedSyntaxListWrapper<TNode> nodes)
            => throw new global::System.NotImplementedException();

        public static implicit operator SeparatedSyntaxListWrapper<TNode>(SeparatedSyntaxListWrapper<SyntaxNode> nodes)
            => throw new global::System.NotImplementedException();

        public static bool Is(object? obj)
        {
            if (obj != null && obj.GetType() != WrappedType)
            {
                obj = null;
            }

            return obj != null;
        }

        public static SeparatedSyntaxListWrapper<TNode> As(object? obj)
        {
            if (obj != null && obj.GetType() != WrappedType)
            {
                obj = null;
            }

            return new SeparatedSyntaxListWrapper<TNode>(obj);
        }

        public readonly object? Unwrap()
            => wrappedObject;

        public readonly global::Microsoft.CodeAnalysis.SyntaxToken GetSeparator(int index)
            => throw new global::System.NotImplementedException();

        public readonly global::System.Collections.Generic.IEnumerable<global::Microsoft.CodeAnalysis.SyntaxToken> GetSeparators()
            => throw new global::System.NotImplementedException();

        public readonly override string ToString()
            => throw new global::System.NotImplementedException();

        public readonly string ToFullString()
            => throw new global::System.NotImplementedException();

        public readonly TNode First()
            => throw new global::System.NotImplementedException();

        public readonly TNode FirstOrDefault()
            => throw new global::System.NotImplementedException();

        public readonly TNode Last()
            => throw new global::System.NotImplementedException();

        public TNode LastOrDefault()
            => throw new global::System.NotImplementedException();

        public readonly bool Contains(TNode node)
            => throw new global::System.NotImplementedException();

        public readonly int IndexOf(TNode node)
            => throw new global::System.NotImplementedException();

        public readonly int IndexOf(global::System.Func<TNode, bool> predicate)
            => throw new global::System.NotImplementedException();

        public readonly int LastIndexOf(TNode node)
            => throw new global::System.NotImplementedException();

        public readonly int LastIndexOf(global::System.Func<TNode, bool> predicate)
            => throw new global::System.NotImplementedException();

        public readonly bool Any()
            => throw new global::System.NotImplementedException();

        public readonly SyntaxNodeOrTokenList GetWithSeparators()
            => throw new global::System.NotImplementedException();

        public readonly SeparatedSyntaxListWrapper<TNode> Add(TNode node)
            => throw new global::System.NotImplementedException();

        public readonly SeparatedSyntaxListWrapper<TNode> AddRange(global::System.Collections.Generic.IEnumerable<TNode> nodes)
            => AddRangeAccessor(wrappedObject, nodes);

        public readonly SeparatedSyntaxListWrapper<TNode> Insert(int index, TNode node)
            => throw new global::System.NotImplementedException();

        public readonly SeparatedSyntaxListWrapper<TNode> InsertRange(int index, global::System.Collections.Generic.IEnumerable<TNode> nodes)
            => throw new global::System.NotImplementedException();

        public readonly SeparatedSyntaxListWrapper<TNode> RemoveAt(int index)
            => throw new global::System.NotImplementedException();

        public readonly SeparatedSyntaxListWrapper<TNode> Remove(TNode node)
            => throw new global::System.NotImplementedException();

        public readonly SeparatedSyntaxListWrapper<TNode> Replace(TNode nodeInList, TNode newNode)
            => throw new global::System.NotImplementedException();

        public readonly SeparatedSyntaxListWrapper<TNode> ReplaceRange(TNode nodeInList, global::System.Collections.Generic.IEnumerable<TNode> newNodes)
            => throw new global::System.NotImplementedException();

        public readonly SeparatedSyntaxListWrapper<TNode> ReplaceSeparator(global::Microsoft.CodeAnalysis.SyntaxToken separatorToken, global::Microsoft.CodeAnalysis.SyntaxToken newSeparator)
            => throw new global::System.NotImplementedException();
    }
}
