// <auto-generated/>
#nullable enable

namespace Microsoft.CodeAnalysis.Lightup
{
    /// <summary>Provides lightup support for class Microsoft.CodeAnalysis.WellKnownMemberNames.</summary>
    public static partial class WellKnownMemberNamesEx
    {
        private const string WrappedTypeName = "Microsoft.CodeAnalysis.WellKnownMemberNames";

        private delegate global::System.String CheckedAdditionOperatorNameGetterDelegate();
        private delegate global::System.String CheckedDecrementOperatorNameGetterDelegate();
        private delegate global::System.String CheckedDivisionOperatorNameGetterDelegate();
        private delegate global::System.String CheckedExplicitConversionNameGetterDelegate();
        private delegate global::System.String CheckedIncrementOperatorNameGetterDelegate();
        private delegate global::System.String CheckedMultiplyOperatorNameGetterDelegate();
        private delegate global::System.String CheckedSubtractionOperatorNameGetterDelegate();
        private delegate global::System.String CheckedUnaryNegationOperatorNameGetterDelegate();
        private delegate global::System.String CountPropertyNameGetterDelegate();
        private delegate global::System.String DeconstructMethodNameGetterDelegate();
        private delegate global::System.String DisposeAsyncMethodNameGetterDelegate();
        private delegate global::System.String DisposeMethodNameGetterDelegate();
        private delegate global::System.String GetAsyncEnumeratorMethodNameGetterDelegate();
        private delegate global::System.String LengthPropertyNameGetterDelegate();
        private delegate global::System.String MoveNextAsyncMethodNameGetterDelegate();
        private delegate global::System.String PrintMembersMethodNameGetterDelegate();
        private delegate global::System.String SliceMethodNameGetterDelegate();
        private delegate global::System.String TopLevelStatementsEntryPointMethodNameGetterDelegate();
        private delegate global::System.String TopLevelStatementsEntryPointTypeNameGetterDelegate();

        private static readonly CheckedAdditionOperatorNameGetterDelegate CheckedAdditionOperatorNameGetterFunc;
        private static readonly CheckedDecrementOperatorNameGetterDelegate CheckedDecrementOperatorNameGetterFunc;
        private static readonly CheckedDivisionOperatorNameGetterDelegate CheckedDivisionOperatorNameGetterFunc;
        private static readonly CheckedExplicitConversionNameGetterDelegate CheckedExplicitConversionNameGetterFunc;
        private static readonly CheckedIncrementOperatorNameGetterDelegate CheckedIncrementOperatorNameGetterFunc;
        private static readonly CheckedMultiplyOperatorNameGetterDelegate CheckedMultiplyOperatorNameGetterFunc;
        private static readonly CheckedSubtractionOperatorNameGetterDelegate CheckedSubtractionOperatorNameGetterFunc;
        private static readonly CheckedUnaryNegationOperatorNameGetterDelegate CheckedUnaryNegationOperatorNameGetterFunc;
        private static readonly CountPropertyNameGetterDelegate CountPropertyNameGetterFunc;
        private static readonly DeconstructMethodNameGetterDelegate DeconstructMethodNameGetterFunc;
        private static readonly DisposeAsyncMethodNameGetterDelegate DisposeAsyncMethodNameGetterFunc;
        private static readonly DisposeMethodNameGetterDelegate DisposeMethodNameGetterFunc;
        private static readonly GetAsyncEnumeratorMethodNameGetterDelegate GetAsyncEnumeratorMethodNameGetterFunc;
        private static readonly LengthPropertyNameGetterDelegate LengthPropertyNameGetterFunc;
        private static readonly MoveNextAsyncMethodNameGetterDelegate MoveNextAsyncMethodNameGetterFunc;
        private static readonly PrintMembersMethodNameGetterDelegate PrintMembersMethodNameGetterFunc;
        private static readonly SliceMethodNameGetterDelegate SliceMethodNameGetterFunc;
        private static readonly TopLevelStatementsEntryPointMethodNameGetterDelegate TopLevelStatementsEntryPointMethodNameGetterFunc;
        private static readonly TopLevelStatementsEntryPointTypeNameGetterDelegate TopLevelStatementsEntryPointTypeNameGetterFunc;

        static WellKnownMemberNamesEx()
        {
            var wrappedType = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.FindType(WrappedTypeName);

            CheckedAdditionOperatorNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<CheckedAdditionOperatorNameGetterDelegate>(wrappedType, nameof(CheckedAdditionOperatorName));
            CheckedDecrementOperatorNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<CheckedDecrementOperatorNameGetterDelegate>(wrappedType, nameof(CheckedDecrementOperatorName));
            CheckedDivisionOperatorNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<CheckedDivisionOperatorNameGetterDelegate>(wrappedType, nameof(CheckedDivisionOperatorName));
            CheckedExplicitConversionNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<CheckedExplicitConversionNameGetterDelegate>(wrappedType, nameof(CheckedExplicitConversionName));
            CheckedIncrementOperatorNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<CheckedIncrementOperatorNameGetterDelegate>(wrappedType, nameof(CheckedIncrementOperatorName));
            CheckedMultiplyOperatorNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<CheckedMultiplyOperatorNameGetterDelegate>(wrappedType, nameof(CheckedMultiplyOperatorName));
            CheckedSubtractionOperatorNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<CheckedSubtractionOperatorNameGetterDelegate>(wrappedType, nameof(CheckedSubtractionOperatorName));
            CheckedUnaryNegationOperatorNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<CheckedUnaryNegationOperatorNameGetterDelegate>(wrappedType, nameof(CheckedUnaryNegationOperatorName));
            CountPropertyNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<CountPropertyNameGetterDelegate>(wrappedType, nameof(CountPropertyName));
            DeconstructMethodNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<DeconstructMethodNameGetterDelegate>(wrappedType, nameof(DeconstructMethodName));
            DisposeAsyncMethodNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<DisposeAsyncMethodNameGetterDelegate>(wrappedType, nameof(DisposeAsyncMethodName));
            DisposeMethodNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<DisposeMethodNameGetterDelegate>(wrappedType, nameof(DisposeMethodName));
            GetAsyncEnumeratorMethodNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<GetAsyncEnumeratorMethodNameGetterDelegate>(wrappedType, nameof(GetAsyncEnumeratorMethodName));
            LengthPropertyNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<LengthPropertyNameGetterDelegate>(wrappedType, nameof(LengthPropertyName));
            MoveNextAsyncMethodNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<MoveNextAsyncMethodNameGetterDelegate>(wrappedType, nameof(MoveNextAsyncMethodName));
            PrintMembersMethodNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<PrintMembersMethodNameGetterDelegate>(wrappedType, nameof(PrintMembersMethodName));
            SliceMethodNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<SliceMethodNameGetterDelegate>(wrappedType, nameof(SliceMethodName));
            TopLevelStatementsEntryPointMethodNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<TopLevelStatementsEntryPointMethodNameGetterDelegate>(wrappedType, nameof(TopLevelStatementsEntryPointMethodName));
            TopLevelStatementsEntryPointTypeNameGetterFunc = global::Microsoft.CodeAnalysis.Lightup.CommonLightupHelper.CreateStaticReadAccessor<TopLevelStatementsEntryPointTypeNameGetterDelegate>(wrappedType, nameof(TopLevelStatementsEntryPointTypeName));
        }

        /// <summary>Field added in version 4.3.0.0.</summary>
        public static global::System.String CheckedAdditionOperatorName
        {
            get { return CheckedAdditionOperatorNameGetterFunc(); }
        }

        /// <summary>Field added in version 4.3.0.0.</summary>
        public static global::System.String CheckedDecrementOperatorName
        {
            get { return CheckedDecrementOperatorNameGetterFunc(); }
        }

        /// <summary>Field added in version 4.3.0.0.</summary>
        public static global::System.String CheckedDivisionOperatorName
        {
            get { return CheckedDivisionOperatorNameGetterFunc(); }
        }

        /// <summary>Field added in version 4.3.0.0.</summary>
        public static global::System.String CheckedExplicitConversionName
        {
            get { return CheckedExplicitConversionNameGetterFunc(); }
        }

        /// <summary>Field added in version 4.3.0.0.</summary>
        public static global::System.String CheckedIncrementOperatorName
        {
            get { return CheckedIncrementOperatorNameGetterFunc(); }
        }

        /// <summary>Field added in version 4.3.0.0.</summary>
        public static global::System.String CheckedMultiplyOperatorName
        {
            get { return CheckedMultiplyOperatorNameGetterFunc(); }
        }

        /// <summary>Field added in version 4.3.0.0.</summary>
        public static global::System.String CheckedSubtractionOperatorName
        {
            get { return CheckedSubtractionOperatorNameGetterFunc(); }
        }

        /// <summary>Field added in version 4.3.0.0.</summary>
        public static global::System.String CheckedUnaryNegationOperatorName
        {
            get { return CheckedUnaryNegationOperatorNameGetterFunc(); }
        }

        /// <summary>Field added in version 3.1.0.0.</summary>
        public static global::System.String CountPropertyName
        {
            get { return CountPropertyNameGetterFunc(); }
        }

        /// <summary>Field added in version 2.7.0.0.</summary>
        public static global::System.String DeconstructMethodName
        {
            get { return DeconstructMethodNameGetterFunc(); }
        }

        /// <summary>Field added in version 3.0.0.0.</summary>
        public static global::System.String DisposeAsyncMethodName
        {
            get { return DisposeAsyncMethodNameGetterFunc(); }
        }

        /// <summary>Field added in version 3.0.0.0.</summary>
        public static global::System.String DisposeMethodName
        {
            get { return DisposeMethodNameGetterFunc(); }
        }

        /// <summary>Field added in version 3.0.0.0.</summary>
        public static global::System.String GetAsyncEnumeratorMethodName
        {
            get { return GetAsyncEnumeratorMethodNameGetterFunc(); }
        }

        /// <summary>Field added in version 3.1.0.0.</summary>
        public static global::System.String LengthPropertyName
        {
            get { return LengthPropertyNameGetterFunc(); }
        }

        /// <summary>Field added in version 3.0.0.0.</summary>
        public static global::System.String MoveNextAsyncMethodName
        {
            get { return MoveNextAsyncMethodNameGetterFunc(); }
        }

        /// <summary>Field added in version 3.10.0.0.</summary>
        public static global::System.String PrintMembersMethodName
        {
            get { return PrintMembersMethodNameGetterFunc(); }
        }

        /// <summary>Field added in version 3.1.0.0.</summary>
        public static global::System.String SliceMethodName
        {
            get { return SliceMethodNameGetterFunc(); }
        }

        /// <summary>Field added in version 3.8.0.0.</summary>
        public static global::System.String TopLevelStatementsEntryPointMethodName
        {
            get { return TopLevelStatementsEntryPointMethodNameGetterFunc(); }
        }

        /// <summary>Field added in version 3.8.0.0.</summary>
        public static global::System.String TopLevelStatementsEntryPointTypeName
        {
            get { return TopLevelStatementsEntryPointTypeNameGetterFunc(); }
        }
    }
}
